name: Manual Build

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      # Prepare source code
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      # Prepare environment
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      # Build and publish
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            OPENTTD_VERSION=${{ env.OPENTTD_VERSION }}
          platforms: ${{ env.ARCH }}
          push: true
          tags: ${{ secrets.DOCKER_USER }}/openttd-server:manual-${{ env.ARCH }}
